version: '3'

networks:
  graphql-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16

services:
#  api:
#    build:
#      context: .
#    container_name: graphql-sample
#    ports:
#      - 8080:8080
#    depends_on:
#      - db
#    environment:
#      JAVA_ENV: dev
#      DATABASE_URL: jdbc:mysql://db:3306/graphql_sample_db
#      DATABASE_USER: root
#      DATABASE_PASSWORD: root

  db:
    image: mysql:latest
    container_name: graphql-sample-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=graphql_sample_db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    networks:
      graphql-network:
        ipv4_address: 172.19.0.5