spring:
  #profiles: ${JAVA_ENV}
#  profiles: dev
  application:
    name:
  datasource:
    url: jdbc:mysql://localhost:3306/graphql_sample_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        enable_lazy_load_no_trans: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8080